"""Add session_token column

Revision ID: 97fb7e90c831
Revises: 630eef00ce33
Create Date: 2025-12-14 07:25:23.874979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '97fb7e90c831'
down_revision: Union[str, Sequence[str], None] = '630eef00ce33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'access_token',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('account', 'refresh_token',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('account', 'id_token',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('account', 'scope',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('account', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('account_user_id_fkey'), 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'])
    op.add_column('session', sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    op.add_column('session', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('session_token_key'), 'session', type_='unique')
    op.create_unique_constraint(None, 'session', ['session_token'])
    op.drop_constraint(op.f('session_user_id_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'])
    op.drop_column('session', 'token')
    op.drop_column('session', 'user_agent')
    op.drop_column('session', 'ip_address')
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'),
               existing_nullable=True)
    op.alter_column('task', 'recurrence',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='recurrencepattern'),
               existing_nullable=True)
    op.drop_constraint(op.f('task_user_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_user_id_fkey'), 'task', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task', 'recurrence',
               existing_type=sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='recurrencepattern'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('task', 'priority',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('task', 'completed_at')
    op.add_column('session', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_user_id_fkey'), 'session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'session', type_='unique')
    op.create_unique_constraint(op.f('session_token_key'), 'session', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('session', 'updated_at')
    op.drop_column('session', 'created_at')
    op.drop_column('session', 'session_token')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(op.f('account_user_id_fkey'), 'account', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('account', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('account', 'scope',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('account', 'id_token',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('account', 'refresh_token',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('account', 'access_token',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
