"""add_title_to_conversations

Revision ID: 3999305f0b81
Revises: 5b0264a3470f
Create Date: 2025-12-28 11:56:28.228035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3999305f0b81'
down_revision: Union[str, Sequence[str], None] = '5b0264a3470f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add title column with default value for existing rows
    op.add_column('conversations', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False, server_default='New Chat'))
    # Remove server default after adding the column (new rows will use model default)
    op.alter_column('conversations', 'title', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
